acme_product_product_admin_home:
    path: ""
    defaults: { _controller: "acme_product.product.controller:homeAction" }
    methods: [GET]

acme_product_product_admin_list:
    path: /list
    defaults: { _controller: "acme_product.product.controller:listAction" }
    methods: [GET|POST]

acme_product_product_admin_new:
    path: /new
    defaults: { _controller: "acme_product.product.controller:newAction" }
    methods: [GET|POST]

acme_product_product_admin_show:
    path: /{productId}/show
    defaults: { _controller: "acme_product.product.controller:showAction" }
    methods: [GET]
    requirements:
        productId: \d+

acme_product_product_admin_edit:
    path: /{productId}/edit
    defaults: { _controller: "acme_product.product.controller:editAction" }
    methods: [GET|POST]
    requirements:
        productId: \d+

acme_product_product_admin_remove:
    path: /{productId}/remove
    defaults: { _controller: "acme_product.product.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        productId: \d+

acme_product_product_admin_search:
    path: /search
    defaults: { _controller: "acme_product.product.controller:searchAction" }
    methods: [GET]
    options:
        expose: true

acme_product_product_admin_find:
    path: /find
    defaults: { _controller: "acme_product.product.controller:findAction" }
    methods: [GET]
    options:
        expose: true

acme_product_stock_unit_admin:
    resource: stock_unit.yml
    prefix: /{productId}/stock-units
