ekyna_commerce:
    country:
        class: Ekyna\Component\Commerce\Common\Entity\Country
        repository: Ekyna\Component\Commerce\Bridge\Doctrine\ORM\Repository\CountryRepository
        form: Ekyna\Bundle\CommerceBundle\Form\Type\CountryType
        actions:
            list:
                table: Ekyna\Bundle\CommerceBundle\Table\Type\CountryType
            create:
                template: EkynaCommerceBundle:Admin/Country:_form.html
            read:
                template: EkynaCommerceBundle:Admin/Country:show.html
            update:
                template: EkynaCommerceBundle:Admin/Country:_form.html
            delete: ~
        behaviors:
            default: ~
            enabled: ~
