ekyna_commerce_country_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.country.controller:homeAction" }
    methods: [GET]

ekyna_commerce_country_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.country.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_country_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.country.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_country_admin_show:
    path: /{countryId}/show
    defaults: { _controller: "ekyna_commerce.country.controller:showAction" }
    methods: [GET]
    requirements:
        countryId: \d+

ekyna_commerce_country_admin_edit:
    path: /{countryId}/edit
    defaults: { _controller: "ekyna_commerce.country.controller:editAction" }
    methods: [GET|POST]
    requirements:
        countryId: \d+

ekyna_commerce_country_admin_toggle:
    path: /{countryId}/toggle/{field}
    defaults: { _controller: "ekyna_commerce.country.controller:toggleAction", field: enabled }
    methods: [GET]
    requirements:
        countryId: \d+
        field: \w+

ekyna_commerce_country_admin_remove:
    path: /{countryId}/remove
    defaults: { _controller: "ekyna_commerce.country.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        countryId: \d+
