ekyna_commerce_currency_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.currency.controller:homeAction" }
    methods: [GET]

ekyna_commerce_currency_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.currency.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_currency_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.currency.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_currency_admin_show:
    path: /{currencyId}/show
    defaults: { _controller: "ekyna_commerce.currency.controller:showAction" }
    methods: [GET]
    requirements:
        currencyId: \d+

ekyna_commerce_currency_admin_edit:
    path: /{currencyId}/edit
    defaults: { _controller: "ekyna_commerce.currency.controller:editAction" }
    methods: [GET|POST]
    requirements:
        currencyId: \d+

ekyna_commerce_currency_admin_toggle:
    path: /{currencyId}/toggle/{field}
    defaults: { _controller: "ekyna_commerce.currency.controller:toggleAction", field: enabled }
    methods: [GET]
    requirements:
        currencyId: \d+
        field: \w+

ekyna_commerce_currency_admin_remove:
    path: /{currencyId}/remove
    defaults: { _controller: "ekyna_commerce.currency.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        currencyId: \d+
