ekyna_commerce_customer_group_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.customer_group.controller:homeAction" }
    methods: [GET]

ekyna_commerce_customer_group_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.customer_group.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_customer_group_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.customer_group.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_customer_group_admin_show:
    path: /{customerGroupId}/show
    defaults: { _controller: "ekyna_commerce.customer_group.controller:showAction" }
    methods: [GET]
    requirements:
        customerGroupId: \d+

ekyna_commerce_customer_group_admin_edit:
    path: /{customerGroupId}/edit
    defaults: { _controller: "ekyna_commerce.customer_group.controller:editAction" }
    methods: [GET|POST]
    requirements:
        customerGroupId: \d+

ekyna_commerce_customer_group_admin_remove:
    path: /{customerGroupId}/remove
    defaults: { _controller: "ekyna_commerce.customer_group.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        customerGroupId: \d+
