ekyna_commerce_order_adjustment_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.order_adjustment.controller:newAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+

ekyna_commerce_order_adjustment_admin_edit:
    path: /{orderAdjustmentId}/edit
    defaults: { _controller: "ekyna_commerce.order_adjustment.controller:editAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+
        orderAdjustmentId: \d+

ekyna_commerce_order_adjustment_admin_remove:
    path: /{orderAdjustmentId}/remove
    defaults: { _controller: "ekyna_commerce.order_adjustment.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+
        orderAdjustmentId: \d+
