ekyna_commerce_order_credit_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.order_credit.controller:newAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+

ekyna_commerce_order_credit_admin_edit:
    path: /{orderCreditId}/edit
    defaults: { _controller: "ekyna_commerce.order_credit.controller:editAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+
        orderCreditId: \d+

ekyna_commerce_order_credit_admin_remove:
    path: /{orderCreditId}/remove
    defaults: { _controller: "ekyna_commerce.order_credit.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+
        orderCreditId: \d+
