ekyna_commerce_order_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.order.controller:homeAction" }
    methods: [GET]

ekyna_commerce_order_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.order.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_order_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.order.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_order_admin_show:
    path: /{orderId}/show
    defaults: { _controller: "ekyna_commerce.order.controller:showAction" }
    methods: [GET]
    requirements:
        orderId: \d+

ekyna_commerce_order_admin_edit:
    path: /{orderId}/edit
    defaults: { _controller: "ekyna_commerce.order.controller:editAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+

#ekyna_commerce_order_admin_toggle:
#    path: /{orderId}/toggle/{field}
#    defaults: { _controller: "ekyna_commerce.order.controller:toggleAction", field: enabled }
#    methods: [GET]
#    requirements:
#        orderId: \d+
#        field: \w+

ekyna_commerce_order_admin_remove:
    path: /{orderId}/remove
    defaults: { _controller: "ekyna_commerce.order.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        orderId: \d+

ekyna_commerce_order_admin_refresh:
    path: /{orderId}/refresh
    defaults: { _controller: "ekyna_commerce.order.controller:refreshAction" }
    methods: [GET]
    requirements:
        orderId: \d+

ekyna_commerce_order_admin_recalculate:
    path: /{orderId}/recalculate
    defaults: { _controller: "ekyna_commerce.order.controller:recalculateAction" }
    methods: [POST]
    requirements:
        orderId: \d+

ekyna_commerce_order_item_admin:
    resource: order_item.yml
    prefix: /{orderId}/items

ekyna_commerce_order_adjustment_admin:
    resource: order_adjustment.yml
    prefix: /{orderId}/adjustments

ekyna_commerce_order_payment_admin:
    resource: order_payment.yml
    prefix: /{orderId}/payments

ekyna_commerce_order_shipment_admin:
    resource: order_shipment.yml
    prefix: /{orderId}/shipments
