ekyna_commerce_payment_term_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.payment_term.controller:homeAction" }
    methods: [GET]

ekyna_commerce_payment_term_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.payment_term.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_payment_term_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.payment_term.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_payment_term_admin_show:
    path: /{paymentTermId}/show
    defaults: { _controller: "ekyna_commerce.payment_term.controller:showAction" }
    methods: [GET]
    requirements:
        paymentTermId: \d+

ekyna_commerce_payment_term_admin_edit:
    path: /{paymentTermId}/edit
    defaults: { _controller: "ekyna_commerce.payment_term.controller:editAction" }
    methods: [GET|POST]
    requirements:
        paymentTermId: \d+

ekyna_commerce_payment_term_admin_remove:
    path: /{paymentTermId}/remove
    defaults: { _controller: "ekyna_commerce.payment_term.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        paymentTermId: \d+
