ekyna_commerce_quote_adjustment_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.quote_adjustment.controller:newAction" }
    methods: [GET|POST]
    requirements:
        quoteId: \d+

ekyna_commerce_quote_adjustment_admin_edit:
    path: /{quoteAdjustmentId}/edit
    defaults: { _controller: "ekyna_commerce.quote_adjustment.controller:editAction" }
    methods: [GET|POST]
    requirements:
        quoteId: \d+
        quoteAdjustmentId: \d+

ekyna_commerce_quote_adjustment_admin_remove:
    path: /{quoteAdjustmentId}/remove
    defaults: { _controller: "ekyna_commerce.quote_adjustment.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        quoteId: \d+
        quoteAdjustmentId: \d+
