ekyna_commerce_shipment_zone_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.shipment_zone.controller:homeAction" }
    methods: [GET]

ekyna_commerce_shipment_zone_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.shipment_zone.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_shipment_zone_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.shipment_zone.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_shipment_zone_admin_show:
    path: /{shipmentZoneId}/show
    defaults: { _controller: "ekyna_commerce.shipment_zone.controller:showAction" }
    methods: [GET]
    requirements:
        shipmentZoneId: \d+

ekyna_commerce_shipment_zone_admin_edit:
    path: /{shipmentZoneId}/edit
    defaults: { _controller: "ekyna_commerce.shipment_zone.controller:editAction" }
    methods: [GET|POST]
    requirements:
        shipmentZoneId: \d+

ekyna_commerce_shipment_zone_admin_remove:
    path: /{shipmentZoneId}/remove
    defaults: { _controller: "ekyna_commerce.shipment_zone.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        shipmentZoneId: \d+
