ekyna_commerce_supplier_delivery_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.supplier_delivery.controller:newAction" }
    methods: [GET|POST]
    requirements:
        supplierOrderId: \d+

ekyna_commerce_supplier_delivery_admin_show:
    path: /{supplierDeliveryId}/show
    defaults: { _controller: "ekyna_commerce.supplier_delivery.controller:showAction" }
    methods: [GET]
    requirements:
        supplierOrderId: \d+
        supplierDeliveryId: \d+

ekyna_commerce_supplier_delivery_admin_edit:
    path: /{supplierDeliveryId}/edit
    defaults: { _controller: "ekyna_commerce.supplier_delivery.controller:editAction" }
    methods: [GET|POST]
    requirements:
        supplierOrderId: \d+
        supplierDeliveryId: \d+

ekyna_commerce_supplier_delivery_admin_remove:
    path: /{supplierDeliveryId}/remove
    defaults: { _controller: "ekyna_commerce.supplier_delivery.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        supplierOrderId: \d+
        supplierDeliveryId: \d+
