ekyna_commerce_supplier_product_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.supplier_product.controller:newAction" }
    methods: [GET|POST]
    requirements:
        supplierId: \d+

ekyna_commerce_supplier_product_admin_show:
    path: /{supplierProductId}/show
    defaults: { _controller: "ekyna_commerce.supplier_product.controller:showAction" }
    methods: [GET]
    requirements:
        supplierId: \d+
        supplierProductId: \d+

ekyna_commerce_supplier_product_admin_edit:
    path: /{supplierProductId}/edit
    defaults: { _controller: "ekyna_commerce.supplier_product.controller:editAction" }
    methods: [GET|POST]
    requirements:
        supplierId: \d+
        supplierProductId: \d+

ekyna_commerce_supplier_product_admin_remove:
    path: /{supplierProductId}/remove
    defaults: { _controller: "ekyna_commerce.supplier_product.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        supplierId: \d+
        supplierProductId: \d+
