ekyna_commerce_tax_rule_admin_home:
    path: ""
    defaults: { _controller: "ekyna_commerce.tax_rule.controller:homeAction" }
    methods: [GET]

ekyna_commerce_tax_rule_admin_list:
    path: /list
    defaults: { _controller: "ekyna_commerce.tax_rule.controller:listAction" }
    methods: [GET|POST]

ekyna_commerce_tax_rule_admin_new:
    path: /new
    defaults: { _controller: "ekyna_commerce.tax_rule.controller:newAction" }
    methods: [GET|POST]

ekyna_commerce_tax_rule_admin_show:
    path: /{taxRuleId}/show
    defaults: { _controller: "ekyna_commerce.tax_rule.controller:showAction" }
    methods: [GET]
    requirements:
        taxRuleId: \d+

ekyna_commerce_tax_rule_admin_edit:
    path: /{taxRuleId}/edit
    defaults: { _controller: "ekyna_commerce.tax_rule.controller:editAction" }
    methods: [GET|POST]
    requirements:
        taxRuleId: \d+

ekyna_commerce_tax_rule_admin_remove:
    path: /{taxRuleId}/remove
    defaults: { _controller: "ekyna_commerce.tax_rule.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        taxRuleId: \d+
