Ekyna\Bundle\CommerceBundle\Entity\Customer:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            access_type: public_method
            groups: [Search, Default]
        company:
            expose: true
            access_type: public_method
            groups: [Search, Default]
        firstName:
            expose: true
#            serialized_name: first_name
            groups: [Search, Default]
        lastName:
            expose: true
#            serialized_name: last_name
            groups: [Search, Default]
        email:
            expose: true
            groups: [Search, Default]
    virtual_properties:
        __toString:
            expose: true
            serialized_name: text
            type: string
            groups: [Search]
