ekyna_commerce_payment_cart_capture:
    path: /capture/{key}
    defaults:
        _controller: ekyna_commerce.payment.cart_controller:captureAction
    requirements:
        key: "[a-zA-Z0-9]+"

ekyna_commerce_payment_cart_cancel:
    path: /cancel/{key}
    defaults:
        _controller: ekyna_commerce.payment.cart_controller:cancelAction
    requirements:
        key: "[a-zA-Z0-9]+"

ekyna_commerce_payment_cart_notify:
    path: /notify
    defaults:
        _controller: ekyna_commerce.payment.cart_controller:notifyAction

ekyna_commerce_payment_cart_done:
    path: /done
    defaults:
        _controller: ekyna_commerce.payment.cart_controller:doneAction
