ekyna_commerce_attribute_group_admin:
    resource: "admin/attribute_group.yml"
    prefix:   /attribute-groups

ekyna_commerce_attribute_set_admin:
    resource: "admin/attribute_set.yml"
    prefix:   /attribute-sets

ekyna_commerce_country_admin:
    resource: "admin/country.yml"
    prefix:   /countries

ekyna_commerce_currency_admin:
    resource: "admin/currency.yml"
    prefix:   /currencies

ekyna_commerce_customer_admin:
    resource: "admin/customer.yml"
    prefix:   /customers

ekyna_commerce_customer_group_admin:
    resource: "admin/customer_group.yml"
    prefix:   /customer-groups

ekyna_commerce_order_admin:
    resource: "admin/order.yml"
    prefix:   /orders

ekyna_commerce_product_admin:
    resource: "admin/product.yml"
    prefix:   /products

ekyna_commerce_quote_admin:
    resource: "admin/quote.yml"
    prefix:   /quotes

ekyna_commerce_tax_admin:
    resource: "admin/tax.yml"
    prefix:   /taxes

ekyna_commerce_tax_group_admin:
    resource: "admin/tax_group.yml"
    prefix:   /tax-groups

ekyna_commerce_tax_rule_admin:
    resource: "admin/tax_rule.yml"
    prefix:   /tax-rules
