ekyna_commerce_payment_cart:
    resource: "payment/cart.yml"
    prefix: /cart
    options: { i18n: false }

ekyna_commerce_payment_quote:
    resource: "payment/quote.yml"
    prefix: /quote
    options: { i18n: false }

ekyna_commerce_payment_order:
    resource: "payment/order.yml"
    prefix: /order
    options: { i18n: false }
